version: '3.8'
services:
  node:
    image: ghcr.io/gnosischain/gbc-prysm-beacon-chain:v2.0.5-gbc
    restart: always
    command: |
      --accept-terms-of-use
      --contract-deployment-block $DEPLOYMENT_BLOCK
      --http-web3provider $XDAI_RPC_URL
      --fallback-web3provider $FALLBACK_XDAI_RPC_URL
      --bootstrap-node /root/sbc/config/bootnodes.yaml
      --config-file /root/sbc/config/config.yml
      --chain-config-file /root/sbc/config/config.yml
      --rpc-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --p2p-local-ip 0.0.0.0
      --p2p-host-ip $PUBLIC_IP
      --monitoring-host 0.0.0.0
      --verbosity $LOG_LEVEL
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '127.0.0.1:4000:4000'
      - '127.0.0.1:3500:3500'
      - '8080:8080'
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  validator:
    image: ghcr.io/gnosischain/gbc-prysm-validator:v2.0.5-gbc
    restart: always
    command: |
      --accept-terms-of-use
      --config-file /root/sbc/config/config.yml
      --chain-config-file /root/sbc/config/config.yml
      --wallet-password-file /root/sbc/keys/wallet_password.txt
      --graffiti-file=/root/sbc/config/graffiti.yml
      --beacon-rpc-provider node:4000
      --monitoring-host 0.0.0.0
    ports:
      - '8081:8081'
    volumes:
      - ./config:/root/sbc/config
      - ./keys:/root/sbc/keys
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
